---
title: "Life Expectancy Modeling"
author: "Satvik"
output: html_notebook
editor_options: 
  chunk_output_type: console
---
```{r}
library(ggthemes)
theme_set(theme_fivethirtyeight())
theme_update(axis.title = element_text()) #the default for fivethirtyeight is to not show axis labels, this removes that default so we can choose to specify and display axis titles
theme_update(plot.title = element_text(hjust = 0.5))
```

```{r}
#Import Clean, Scaled, and Transformed CSV 
cst.df <- read.csv("https://raw.githubusercontent.com/JosephLazarus/Life_Expectancy/main/Data_Folder/clean_scaled.csv", header = TRUE, fileEncoding="UTF-8-BOM")

cst.df$Developed = as.factor(cst.df$Developed) 
#Import cleaned scaled 
#import cleaned

#Must omit values before running model
cst.df <- na.omit(cst.df)
```

```{r}
#Train / Test split by Year
cst.training <- cst.df[c(cst.df$Year <= 2010),]
cst.test <- cst.df[c(cst.df$Year > 2010),]

dim(cst.df)
dim(cst.training)
dim(cst.test)

cst.training <- subset(cst.training, select = -c(Country,Year))
cst.test <- subset(cst.test, select = -c(Country, Year))
```


```{r}
library(glmnet)
fitControl<-trainControl(method="repeatedcv",number=10,repeats=10)
# fitControl<-trainControl(method="none")

#GLM Net Model (selecting tuning parameters alpha and lambda via 10 FOLD CV)
# set.seed(1234)
cst.glmnet.fit<-train(Life.expectancy~.,
               data=cst.training,
               method="glmnet",
               trControl = fitControl,
               na.action = na.omit
               )
#glmnet.fit results
cst.glmnet.fit
#Model Coefficients
coef(cst.glmnet.fit$finalModel,cst.glmnet.fit$finalModel$lambdaOpt)
```

```{r}
#Creating using the test set. Resulting in the RMSE of the validation set
cst.glmnet.pred<-predict(cst.glmnet.fit, newdata = cst.test[,-1], observed = cst.test[,1])
RMSE(cst.glmnet.pred, cst.test$Life.expectancy)

#RMSE
glmnet.RMSE<-sqrt(mean((cst.test$Life.expectancy-glmnet.pred)^2))
glmnet.RMSE
plot(cst.glmnet.pred, cst.test$Life.expectancy, ylim=c(40,100), xlim=c(40,100))
lines(0:100,0:100)


#Here is a more natural tool to compute RMSE as well as some additional metrics
cst.glmnet.resamp<-postResample(pred = cst.glmnet.pred, obs = cst.test$Life.expectancy)
cst.glmnet.resamp

#Ranking of the predictors
varImp(cst.glmnet.fit)
plot(varImp(cst.glmnet.fit))
```

```{r}
X <- model.matrix(Life.expectancy~.,cst.training)[,-1]

y <- cst.training$Life.expectancy

xTest <- model.matrix(Life.expectancy~.,cst.test)[,-1]

yTest <- cst.test$Life.expectancy

lambdaGrid = 10^seq(10,-2, length =100)

cst.Lasso<-train(y = y,
             x = X,
             method = 'glmnet',
             tuneGrid = expand.grid(alpha = 1, lambda = lambdaGrid),
             na.action = na.omit
             )

cst.Ridge <-train(y = y, 
              x = X,
              method = 'glmnet',
              tuneGrid = expand.grid(alpha = 0, lambda = lambdaGrid),
              na.action = na.omit
              )

cst.Lasso.pred <- cst.Lasso %>% predict(xTest)
cst.Ridge.pred <- cst.Lasso %>% predict(xTest)

cst.Lasso_RMSE = RMSE(cst.Lasso.pred, yTest)
cst.Lasso_RMSE

cst.Ridge_RMSE = RMSE(cst.Ridge.pred, yTest)
cst.Ridge_RMSE

#Post resample for Lasso Model
Lasso.test <-postResample(pred = cst.Lasso.pred, obs = cst.test$Life.expectancy)
Lasso.test

Ridge.test<-postResample(pred = cst.Ridge.pred, obs = cst.test$Life.expectancy)
Ridge.test

coef(cst.Lasso$finalMode,cst.Lasso$finalModel$lambdaOpt)

varImp(cst.Lasso)
plot(varImp(cst.Lasso))

coef(cst.Ridge$finalModel,cst.Ridge$finalModel$lambdaOpt)

varImp(cst.Ridge)
plot(varImp(cst.Ridge))
```


```{r}

fitControlForward<-trainControl(method="cv")
cst.f.fit<-train(x=X,
             y=y,
             method="leapForward",
             trControl=fitControlForward,
             tuneGrid = expand.grid(nvmax = seq(1, 12, 1))
             )
cst.f.fit
plot(cst.f.fit)
varImp(cst.f.fit)
coef(f.fit$finalModel,f.fit$finalModel$nrbar)
```


```{r}
#21 nu
# n is number of obs
# k is number of parameters
#

AIC <- function(y, y_pred, n, k){
  resids = y - y_pred
  sse = sum(resids^2)
  AIC =  n * log(sse/n) + 2*(k + 1)
  print(return(AIC))
}
knn.38AIC <- AIC(data.mod.knnt3$observed, data.mod.knnt3$predicted, nrow(data.mod.knnt3), 21)
```


```{r}

cst.lm.df.5var <- data.frame(predicted = predict(knnt3, newdata = cs.testing.data[-1]), observed= cs.testing.data[,1])

```



